package com.eternamente.app.domain.model

/**
 * On-device ML prediction of mild cognitive impairment (MCI) risk,
 * generated by the TensorFlow Lite model from recent [GameResult] history.
 *
 * Predictions are computed locally — no raw game data is sent to the cloud.
 * Only the final [riskScore] and [alertLevel] may be shared with caregivers
 * or clinicians, subject to the user's consent settings.
 *
 * @property id Unique identifier (UUID v4).
 * @property userId Identifier of the evaluated [User].
 * @property predictionDate Timestamp when the prediction was computed in epoch milliseconds.
 * @property riskScore Continuous MCI risk score in the range [0.0, 1.0].
 *   Values below 0.3 map to [AlertLevel.NORMAL], 0.3–0.6 to [AlertLevel.WATCH],
 *   and above 0.6 to [AlertLevel.ALERT] (thresholds configurable via ML model metadata).
 * @property alertLevel Discretized risk level derived from [riskScore] — see [AlertLevel].
 * @property domainsFlagged Cognitive domains whose recent score trajectories contributed
 *   most to the elevated risk signal (SHAP-equivalent feature importances).
 * @property explanation Human-readable, lay-language summary of the key risk factors,
 *   generated from a template parameterized by the model's feature importance output.
 */
data class MlPrediction(
    val id: String,
    val userId: String,
    val predictionDate: Long,
    val riskScore: Float,
    val alertLevel: AlertLevel,
    val domainsFlagged: List<CognitiveDomain>,
    val explanation: String
) {

    /**
     * Returns `true` if any cognitive domain has been flagged as a risk contributor.
     */
    val hasDomainFlags: Boolean get() = domainsFlagged.isNotEmpty()

    /**
     * Returns `true` if this prediction requires immediate attention from a caregiver
     * or clinician (i.e., [alertLevel] is [AlertLevel.ALERT]).
     */
    val requiresAttention: Boolean get() = alertLevel == AlertLevel.ALERT
}
